/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverOccurrencesRouteImport } from './routes/driver.occurrences'
import { Route as DriverDeliveriesRouteImport } from './routes/driver.deliveries'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOccurrencesRoute = DriverOccurrencesRouteImport.update({
  id: '/driver/occurrences',
  path: '/driver/occurrences',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/driver/deliveries',
  path: '/driver/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/occurrences': typeof DriverOccurrencesRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/occurrences': typeof DriverOccurrencesRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/occurrences': typeof DriverOccurrencesRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/driver/deliveries'
    | '/driver/occurrences'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/driver/deliveries' | '/driver/occurrences' | '/driver'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/driver/deliveries'
    | '/driver/occurrences'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverOccurrencesRoute: typeof DriverOccurrencesRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/occurrences': {
      id: '/driver/occurrences'
      path: '/driver/occurrences'
      fullPath: '/driver/occurrences'
      preLoaderRoute: typeof DriverOccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/driver/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverOccurrencesRoute: DriverOccurrencesRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
