// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = "https://owlbzwsdcognrgolvnzg.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bGJ6d3NkY29nbnJnb2x2bnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5OTQ1NTMsImV4cCI6MjA5NTU3MDU1M30.R6-FUqubIr3uABzv1CS7jiS5cwygrNiIqk4oNbq7O44";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export function ensureRealtimeConnected() {
  try {
    if (_supabase && (_supabase as any).realtime) {
      const rt = (_supabase as any).realtime;
      const status = typeof rt.isConnected === "function" ? rt.isConnected() : true;
      if (!status) {
        console.log("[Supabase Realtime] Reconectando canal após suspensão do app...");
        try { rt.disconnect(); } catch (e) {}
        rt.connect();
      }
    }
  } catch (e) {
    console.warn("[Supabase Realtime] Falha ao reconectar:", e);
  }
}

if (typeof window !== "undefined") {
  window.addEventListener("pageshow", () => {
    ensureRealtimeConnected();
  });
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "visible") {
      ensureRealtimeConnected();
    }
  });
  window.addEventListener("online", () => {
    ensureRealtimeConnected();
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

